# Generated by Django 4.1.4 on 2024-02-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='company_certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
