# Generated by Django 5.0.4 on 2024-05-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_register_college_certificate_register_college_desc'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='register',
            name='college_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='collegecode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='passoutyear',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='uploadresume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='experience',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
