# Generated by Django 5.0.4 on 2024-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_register_gender_register_city_register_college_name_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select Gender'), ('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
