# Generated by Django 5.0.4 on 2024-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_register_gender_alter_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
