# Generated by Django 5.0.4 on 2024-05-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_register_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='MNC',
            field=models.CharField(choices=[('Select', 'Select Gender'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='companyLicenceid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
