# Generated by Django 5.0.4 on 2024-05-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_register_mnc_register_companylicenceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='MNC',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
