# Generated by Django 5.0.4 on 2024-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_register_college_section_register_number_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
