# Generated by Django 5.0.4 on 2024-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='It_park_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
