# Generated by Django 5.0.4 on 2024-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_interships'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvaccancies',
            name='int_type',
            field=models.IntegerField(null=True),
        ),
    ]
