# Generated by Django 5.0.4 on 2024-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_jobvaccancies_int_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvaccancies',
            name='interviewtime',
            field=models.TimeField(null=True),
        ),
    ]
