# Generated by Django 5.0.4 on 2024-05-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_interships_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interships',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
