# Generated by Django 5.0.4 on 2024-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_visitrequests_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequests',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
