# Generated by Django 5.0.4 on 2024-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_visitrequests_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequests',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
