# Generated by Django 5.0.4 on 2024-05-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_visitrequests_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interships',
            name='int_type',
            field=models.IntegerField(null=True),
        ),
    ]
