# Generated by Django 5.0.4 on 2024-05-28 01:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request_chat',
        ),
    ]
