# Generated by Django 4.2.7 on 2024-06-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_rename_request_request_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interships',
            name='image',
        ),
    ]
