# Generated by Django 5.0.4 on 2024-06-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_remove_interships_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvaccancies',
            name='Location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
