# Generated by Django 5.0.4 on 2024-05-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_visitrequests_resume'),
        ('Jobseaker', '0002_rename_visitrequests_applyjos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjos',
            name='Company_id',
        ),
        migrations.AddField(
            model_name='applyjos',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvc', to='Company.jobvaccancies'),
        ),
    ]
