# Generated by Django 5.0.4 on 2024-05-11 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_interships_int_type'),
        ('Jobseaker', '0003_remove_applyjos_company_id_applyjos_job_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='savedjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='j', to='Company.jobvaccancies')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
